#!/bin/bash

export PW=`cat password`

# Create a JKS keystore that trusts the actorbase CA, with the default password.
# This is used by the client in the trustmanager section.
keytool -import -v \
  -alias actorbaseca \
  -file actorbaseca.crt \
  -keypass:env PW \
  -storepass abcdefg \
  -keystore actorbasetrust.jks << EOF
yes
EOF

# List out the details of the store password.
keytool -list -v \
  -keystore actorbasetrust.jks \
  -storepass abcdefg
